export const doctors = [
   {
      id: 1,
      name: "Dr. Tarikul Islam",
      image: "https://xsgames.co/randomusers/avatar.php?g=male",
      specialization: "Cardiology",
      qualification: "MBBS, BCS (Health), MPhil (Pathology)",
      experience: 5,
      hospital: "Unity Aid Hospital Ltd.",
      address: "House #16, Road # 2, Dhanmondi R/A, 6, Dhanmondi, Dhaka-1205, Bangladesh",
      availability: ["Sat", "Sun", "Mon"],
      rating: 4.8,
   },
   {
      id: 2,
      name: "Dr. Sarah Johnson",
      image: "https://xsgames.co/randomusers/avatar.php?g=female",
      specialization: "Neurology",
      qualification: "MD, PhD in Neuroscience",
      experience: 8,
      hospital: "Central Neurology Center",
      address: "123 Brain St, Neurocity, NC 54321",
      availability: ["Mon", "Wed", "Fri"],
      rating: 4.9,
   },
   {
      id: 3,
      name: "Dr. Michael Chen",
      image: "https://xsgames.co/randomusers/avatar.php?g=male",
      specialization: "Orthopedics",
      qualification: "MBBS, MS (Orthopedics)",
      experience: 7,
      hospital: "Joint & Spine Clinic",
      address: "456 Bone Ave, Skeletown, ST 98765",
      availability: ["Tue", "Thu", "Sat"],
      rating: 4.7,
   },
   {
      id: 4,
      name: "Dr. Sarah Johnson",
      image: "https://xsgames.co/randomusers/avatar.php?g=male",
      specialization: "Neurology",
      qualification: "MD, PhD in Neuroscience",
      experience: 8,
      hospital: "Central Neurology Center",
      address: "123 Brain St, Neurocity, NC 54321",
      availability: ["Mon", "Wed", "Fri"],
      rating: 4.9,
   },
   {
      id: 5,
      name: "Dr. Michael Chen",
      image: "https://xsgames.co/randomusers/avatar.php?g=male",
      specialization: "Orthopedics",
      qualification: "MBBS, MS (Orthopedics)",
      experience: 7,
      hospital: "Joint & Spine Clinic",
      address: "456 Bone Ave, Skeletown, ST 98765",
      availability: ["Tue", "Thu", "Sat"],
      rating: 4.7,
   },
];
